name: emotunes_app
description: "An emotion-based music recommendation app using facial expression detection"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  camera: ^0.11.1
  tflite_flutter: ^0.11.0
  provider: ^6.0.5
  http: ^1.3.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.2.3
  just_audio: ^0.9.34
  flutter_dotenv: ^5.1.0
  permission_handler: ^11.4.0
  path_provider: ^2.0.15
  shared_preferences: ^2.1.2
  logging: ^1.2.0
  firebase_core: ^3.12.1 
  firebase_auth: 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
  test: ^1.24.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - .env.example
    - assets/models/
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false