// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDypYphYoDKPNA5S3ew23k9H8hWKVo2T_0',
    appId: '1:921582140767:web:3637410983856edc9e8aea',
    messagingSenderId: '921582140767',
    projectId: 'emotunes-app',
    authDomain: 'emotunes-app.firebaseapp.com',
    storageBucket: 'emotunes-app.firebasestorage.app',
    measurementId: 'G-3MRTK74T60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABJBpWQn5xgVJ9IcFWrULnuJ_cC60zO84',
    appId: '1:921582140767:android:cbb8ffc6a52122c39e8aea',
    messagingSenderId: '921582140767',
    projectId: 'emotunes-app',
    storageBucket: 'emotunes-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGs9Kr1fBqtmVzYg01r7Pf6ck-x4R084g',
    appId: '1:921582140767:ios:d5d998e800ba68b69e8aea',
    messagingSenderId: '921582140767',
    projectId: 'emotunes-app',
    storageBucket: 'emotunes-app.firebasestorage.app',
    iosBundleId: 'com.example.emotunesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGs9Kr1fBqtmVzYg01r7Pf6ck-x4R084g',
    appId: '1:921582140767:ios:d5d998e800ba68b69e8aea',
    messagingSenderId: '921582140767',
    projectId: 'emotunes-app',
    storageBucket: 'emotunes-app.firebasestorage.app',
    iosBundleId: 'com.example.emotunesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDypYphYoDKPNA5S3ew23k9H8hWKVo2T_0',
    appId: '1:921582140767:web:2c212077524c1da39e8aea',
    messagingSenderId: '921582140767',
    projectId: 'emotunes-app',
    authDomain: 'emotunes-app.firebaseapp.com',
    storageBucket: 'emotunes-app.firebasestorage.app',
    measurementId: 'G-EE9ZKPYPTN',
  );
}
